### ISSUE TITLE
Can't start postgresql

### ISSUE THREAD

**Issue by cavallium** [postgrespro/lsm3#7]
If I add lsm3 to preloaded libraries I get this error:
`cannot request additional shared memory outside shmem_request_hook`

**Comment by knizhnik** [comment]
I am sorry for delay with answer.
Fixed!

**Comment by cavallium** [comment]
> I am sorry for delay with answer. Fixed!

```
lsm3.c: In function ‘lsm3_build_empty’:
lsm3.c:817:29: error: ‘SMgrRelationData’ has no member named ‘smgr_rlocator’
  817 |  log_newpage(&index->rd_smgr->smgr_rlocator.locator, MAIN_FORKNUM,
      |                             ^~
make: *** [<builtin>: lsm3.o] Error 1
```

**Comment by knizhnik** [comment]
> > I am sorry for delay with answer. Fixed!
> 
> ```
> lsm3.c: In function ‘lsm3_build_empty’:
> lsm3.c:817:29: error: ‘SMgrRelationData’ has no member named ‘smgr_rlocator’
>   817 |  log_newpage(&index->rd_smgr->smgr_rlocator.locator, MAIN_FORKNUM,
>       |                             ^~
> make: *** [<builtin>: lsm3.o] Error 1
> ```

Sorry, it change from PG-16.
Fixed.
